remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: "Hussein Serhan"
name: "Hussein Serhan"
description: "Fintech Professional | Community Builder"
url: "https://husseinserhan.com"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
search: true

# Site Author
author:
  name: "Hussein Serhan"
  bio: "Fintech professional based in Toronto. Venezuelan background, focused on building bridges in tech."
  location: "Toronto, Canada"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/whosamesirhan"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/whosamesirhan"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
